name: zenazon
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  flutter_sizer: ^1.0.5
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  camera: ^0.10.5+5
  # flashlight: ^0.1.1
  image_picker: ^1.0.4
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
